### ISSUE TITLE
DeNovoGBS, max k-mer size

### ISSUE THREAD

**Issue by MWSchmid** [NGSEP/NGSEPcore#37]
Hi there

Thanks for the nice tool. 

A question regarding the k-mer size in DeNovoGBS. I just tried increasing it to 101, but I get an error:

"The maximum k-mer size for this class is 31."

Is there a way to bypass this? Or is it pointless anyway to use k-mers larger than 31?

Best regards,

Marc

**Comment by jduitama** [comment]
Hi Marc

Thanks for your interest in our new function and my apologies for the late answer. Due to technical constraints with the algorithm design, we set the maximum k-mer size to 31. Larger values will significantly increase the memory consumption and are not likely to make an improvement in clustering or genotyping quality.

Best regards

Jorge
